const layers=[
["01","NEURA","AI operating interface","Context-aware agents coordinate work, surface exceptions and route material decisions to people."],
["02","WORKFLOW ENGINE","Governed execution","Turn operating procedures into measurable workflows with approvals, audit trails and escalation."],
["03","INTEGRATION FABRIC","Connect what already works","Vendor-independent adapters connect incumbent software, structured data, communications and devices."],
["04","NEURATEC CORE","Control plane","Identity, roles, events, canonical data and policy form the reusable foundation beneath every vertical."]
];
const industries=[
["DENTAL","Neura Dental","Connect front office, communications, scheduling and clinical-adjacent workflows without replacing the practice management system."],
["AUTOMOTIVE","Neura Auto","Orchestrate reception, diagnosis, authorization, parts, repair, quality control and follow-up across the shop."],
["FIELD OPERATIONS","Distributed execution","Coordinate service networks, dispatch, evidence and governed actions across people, systems and future edge nodes."]
];
const proofs=[
["JC DENTAL","Curve Dental environment","Integration laboratory for dental workflows and reusable platform patterns."],
["WCDA","Dentrix + DEXIS environment","A second dental environment used to test system independence and deployment patterns."],
["S&A AUTO CENTER","Shop management ecosystem","Automotive operations laboratory focused on workflow control, parts, communications and operational visibility."]
];
export default function Home(){return <main>
<header className="nav"><a className="brand" href="#top" aria-label="NeuraTec home"><span className="dnaMark" aria-hidden="true"><i/><i/><i/><i/></span><span>Neura<span className="tec">Tec</span><small>CORPORATION</small></span></a><nav aria-label="Primary navigation"><a href="#platform">Platform</a><a href="#industries">Industries</a><a href="#proof">Proof</a><a href="#research">Research</a><a href="#company">Company</a></nav><a className="button compact" href="#contact">Explore a pilot ↗</a></header>
<section id="top" className="hero"><div className="heroCopy"><div className="eyebrow">AI OPERATING INFRASTRUCTURE&nbsp;&nbsp;|&nbsp;&nbsp;2026</div><h1>AI should not just answer.<br/><em>It should operate.</em></h1><p className="lead">NeuraTec connects AI agents, workflows, existing systems and people into one governed operational layer for real-world businesses.</p><div className="actions"><a className="button" href="#contact">Build a governed pilot →</a><a className="textLink" href="#platform">Explore the platform ↓</a></div><div className="micro">PEOPLE <i/> PROCESSES <i/> SYSTEMS <i/> AI <i/> REAL RESULTS</div></div><div className="visual" aria-hidden="true"><div className="globe"/><div className="orbit o1"/><div className="orbit o2"/><div className="orbit o3"/><div className="core dnaCore"><span className="dnaBig"><i/><i/><i/><i/><i/></span><strong>Neura<span>Tec</span></strong><small>CORPORATION</small></div><b className="node n1">AI AGENTS<br/>IN OPERATION</b><b className="node n2">END-TO-END<br/>WORKFLOWS</b><b className="node n3">GOVERNANCE<br/>& COMPLIANCE</b></div></section>
<section className="manifesto"><div className="eyebrow">THE OPERATING GAP</div><h2>Keep the systems that work.<br/>Add the intelligence layer that makes them <em>operate together.</em></h2><p>Most businesses do not need another isolated AI tool. They need a governed layer that can understand context, coordinate work across incumbent systems and keep people in authority when decisions matter.</p></section>
<section id="platform" className="section"><div className="sectionHead"><div><span>01 / PLATFORM</span><p>REUSABLE CORE</p></div><h2>One operational layer.<br/>Four governed dimensions.</h2></div><div className="layerGrid">{layers.map(x=><article key={x[0]}><b>{x[0]}</b><div className="line"/><h3>{x[1]}</h3><h4>{x[2]}</h4><p>{x[3]}</p></article>)}</div><div className="architecture"><span>EXISTING BUSINESS SYSTEMS</span><i>→</i><strong>INTEGRATION FABRIC</strong><i>→</i><strong>NEURATEC CORE</strong><i>→</i><strong>NEURA</strong><i>→</i><span>PEOPLE + OUTCOMES</span></div></section>
<section id="industries" className="section black"><div className="sectionHead"><div><span>02 / INDUSTRIES</span><p>VERTICAL LABS</p></div><h2>Prove it in real operations.<br/>Reuse what works.</h2></div><div className="industryList">{industries.map((x,i)=><article key={x[0]}><b>0{i+1}</b><div><span>{x[0]}</span><h3>{x[1]}</h3><p>{x[2]}</p></div><a href="#contact" aria-label={"Discuss "+x[1]}>↗</a></article>)}</div></section>
<section id="proof" className="section proof"><div className="sectionHead"><div><span>03 / PROOF</span><p>GOVERNED LABS</p></div><h2>Evidence before claims.</h2></div><p className="intro">Our early environments are laboratories for integration, workflow design and reusable IP. They are not presented as finished commercial case studies until measured outcomes exist.</p><div className="proofGrid">{proofs.map((x,i)=><article key={x[0]}><span>LAB 0{i+1}</span><h3>{x[0]}</h3><h4>{x[1]}</h4><p>{x[2]}</p><b>VALIDATION IN PROGRESS</b></article>)}</div></section>
<section className="section governance"><div><span>04 / GOVERNANCE</span><h2>Machine speed.<br/><em>Human authority.</em></h2><p>Automation should expand operational capacity without obscuring responsibility. Material actions stay behind explicit permissions, approval gates and auditability.</p></div><div className="terminal"><header>NEURATEC / POLICY CONTROL</header><p><b>01</b> Identity & role boundaries <i>ACTIVE</i></p><p><b>02</b> Material-action approvals <i>ACTIVE</i></p><p><b>03</b> Audit trails & evidence <i>ACTIVE</i></p><p><b>04</b> Rollback & escalation <i>ACTIVE</i></p><p><b>05</b> Vendor independence <i>ACTIVE</i></p><footer>FINAL AUTHORITY <strong>HUMAN</strong></footer></div></section>
<section id="research" className="section research"><div className="sectionHead"><div><span>05 / RESEARCH</span><p>BUILDING FOR WHAT'S NEXT</p></div><h2>From digital agents<br/>to the physical edge.</h2></div><div className="researchGrid"><article><span>NOW</span><h3>Agentic Operations</h3><p>Operational agents, integration, governed execution and measurable outcomes.</p></article><article><span>NEXT</span><h3>Edge & Private AI</h3><p>Local and private deployment when latency, resilience, privacy or client need justify it.</p></article><article><span>OPTION</span><h3>Physical AI</h3><p>Devices and robotics become adapters to the operating layer when real operational demand earns their place.</p></article></div></section>
<section id="company" className="company"><div><span>NEURATEC CORPORATION</span><h2>Built in New Jersey.<br/>Designed for real-world operations.</h2></div><div><p>NeuraTec is evolving from traditional technology services toward an AI-native operating and integration platform. We combine practical infrastructure experience with software, automation and governed AI.</p><p>Our doctrine is simple: observe, integrate, orchestrate, enhance — and absorb functionality only when doing so creates durable value.</p></div></section>
<section id="contact" className="cta"><div><span>DESIGN PARTNER / PILOT</span><h2>Bring us one operational bottleneck.</h2><p>We will map the workflow, the systems involved, the human decision points and the measurable outcome before proposing automation.</p></div><div className="ctaBox"><p>START A CONVERSATION</p><a className="button inverse" href="mailto:info@us-neuratec.com?subject=NeuraTec%20Pilot%20Conversation">info@us-neuratec.com ↗</a><small>New Jersey · United States</small></div></section>
<footer className="footer"><a className="brand" href="#top"><span className="dnaMark" aria-hidden="true"><i/><i/><i/><i/></span><span>Neura<span className="tec">Tec</span><small>CORPORATION</small></span></a><div><a href="#platform">Platform</a><a href="#industries">Industries</a><a href="#proof">Proof</a><a href="#research">Research</a></div><p>© 2026 NeuraTec Corporation<br/>AI Operating & Integration Infrastructure</p></footer>
</main>}