const solutions=[
["☁","Cloud & Infrastructure","Modern, scalable and secure infrastructure engineered around uptime, performance and growth."],
["⬡","Cybersecurity","Identity, segmentation, resilience, backup and recovery designed into the environment."],
["✦","AI + Automation","Intelligent agents and governed workflows that reduce repetitive work and accelerate operations."],
["◉","Managed IT Services","Accountable support for users, devices, Microsoft 365 and day-to-day technology operations."]
];
const industries=[["♡","Healthcare & Dental"],["◇","Automotive & Service"],["▦","Technology & IT"],["◎","Professional Services"],["▥","Multi-Location & B2B"],["⌁","Manufacturing & Logistics"],["•••","Custom Solutions"]];
export const metadata={title:"NeuraTec Corporation | Enterprise Technology + AI Operations",description:"Managed IT, AI automation, cybersecurity, cloud infrastructure and custom technology systems for modern businesses."};
export default function Home(){return <main className="vFinal">
<nav className="vNav"><a className="vBrand" href="#"><span className="vMark">⌁</span><span>Neura<b>Tec</b><small>CORPORATION</small></span></a><div><a href="#solutions">Solutions⌄</a><a href="#industries">Industries⌄</a><a href="#ai">AI + Automation⌄</a><a href="#about">About</a><a href="#resources">Resources⌄</a></div><a className="vPrimary" href="#contact">Build with us <b>→</b></a></nav>
<section className="vHero"><div className="vBackdrop"/><div className="vHeroCopy"><span>ENTERPRISE TECHNOLOGY / AI-NATIVE OPERATIONS</span><h1>Technology should<br/>not just support.<br/><em>It should operate.</em></h1><p>NeuraTec designs, integrates, secures and operates the technology modern businesses depend on — from infrastructure and cybersecurity to AI, automation and custom business systems.</p><div className="vActions"><a href="#contact">Start a conversation <b>→</b></a><a href="#solutions">Explore capabilities</a></div></div>
<div className="vHub"><div className="vSphere"><i/><i/><strong>N</strong></div><article className="hub1"><b>☁</b><div><strong>Managed IT & Cloud</strong><span>Secure, scalable infrastructure.</span></div></article><article className="hub2"><b>⬡</b><div><strong>Cybersecurity</strong><span>Protect data, people and operations.</span></div></article><article className="hub3"><b>✦</b><div><strong>AI + Automation</strong><span>Turn manual work into intelligent workflows.</span></div></article><article className="hub4"><b>↗</b><div><strong>Strategic IT Advisory</strong><span>Align technology with business goals.</span></div></article><article className="hub5"><b>▦</b><div><strong>Microsoft 365</strong><span>Modern collaboration and productivity.</span></div></article><article className="hub6"><b>⌘</b><div><strong>Custom Solutions</strong><span>Purpose-built systems for unique needs.</span></div></article></div></section>
<section className="vEvidence"><article><b>ONE</b><span>Technology partner</span></article><article><b>END-TO-END</b><span>Infrastructure to AI</span></article><article><b>GOVERNED</b><span>Security + human authority</span></article><article><b>BUILT TO FIT</b><span>Technology around your operation</span></article></section>
<section id="solutions" className="vSolutions"><header><span>OUR SOLUTIONS</span><h2>End-to-end technology<br/><em>for what’s next.</em></h2><p>From day-to-day IT operations to AI-driven transformation, NeuraTec delivers secure, scalable and intelligent solutions designed around how your business actually works.</p><a href="#contact">View all solutions →</a></header><div className="vSolutionCards">{solutions.map(([ic,t,d],i)=><article key={t} className={"sol"+i}><div className="vPhoto"><b>{ic}</b><i/></div><h3>{t}</h3><p>{d}</p><a href="#contact">→</a></article>)}</div></section>
<section id="ai" className="vAi"><div className="vAiVisual"><div className="vAiOrb"><strong>AI</strong><span>IN YOUR BUSINESS</span></div><div className="vAiNode nA">PEOPLE</div><div className="vAiNode nB">SYSTEMS</div><div className="vAiNode nC">DATA</div><div className="vAiNode nD">WORKFLOWS</div></div><div className="vAiCopy"><span>AI FOR REAL OPERATIONS</span><h2>Move AI out of<br/>the chat window.</h2><p>We build intelligent operating experiences around your existing business — connecting people, systems, data and governed AI execution.</p><ul><li>AI agents with defined responsibilities</li><li>Human approval for material actions</li><li>Integration with existing business systems</li><li>Permissions, auditability and operational control</li></ul></div></section>
<section id="industries" className="vIndustries"><header><span>INDUSTRIES WE SERVE</span><h2>Tailored solutions<br/><em>for real operations.</em></h2></header><div>{industries.map(([ic,t])=><article key={t}><b>{ic}</b><span>{t}</span></article>)}</div></section>
<section id="about" className="vAbout"><div><span>ONE TECHNOLOGY PARTNER</span><h2>Infrastructure beneath.<br/><em>Intelligence above.</em></h2><p>Networks, cloud, security, software, data and intelligent automation engineered as one business-aligned environment.</p></div><div className="vStack"><article><b>AI + AUTOMATION</b><span>Agents · orchestration · governed execution</span></article><article><b>APPLICATIONS + WORKFLOWS</b><span>Portals · dashboards · operational systems</span></article><article><b>DATA + INTEGRATION</b><span>APIs · events · connected information</span></article><article><b>IDENTITY + SECURITY</b><span>Access · policy · resilience · continuity</span></article><article><b>CLOUD + SERVERS + NETWORK + EDGE</b><span>The infrastructure everything runs on</span></article></div></section>
<section id="contact" className="vContact"><span>START WITH THE BUSINESS PROBLEM</span><h2>What should technology<br/>do better for you?</h2><p>Tell us where the friction is. We’ll design the technology around the operation.</p><a href="mailto:contact@us-neuratec.com">BUILD WITH NEURATEC →</a></section>
<footer><b>NeuraTec Corporation</b><span>Enterprise Technology · AI-Native Operations</span><span>© 2026</span></footer>
</main>}